### ISSUE TITLE
Not working after reboot

### ISSUE THREAD

**Issue by Web-E** [MrMEEE/ironhide#18]
Today I have done a clean install and reinstalled all the stuff as it worked earlier.
Tried `optirun glxgears`, it was working giving >600 FPS .
I rebooted the system and now it is not working.
``` rajeswar@Web-E:~$ optirun glxgears \* Starting Ironhide X server ironhide                                          _PS0 Enabling nVidia 
Card Succeded.
 FATAL: Error inserting nvidia_current (/lib/modules/2.6.38-8-generic/updates/dkms/nvidia-current.ko): No such device
... \* The nvidia driver was not loaded, try: sudo modprobe nvidia-current        \* The Ironhide Xserver failed to start. Please 
check /var/log/Xorg.8.log[fail] 
 ironhide could not be started - optirun cannot be executed.

``````
But the nvidia drivers are already installed.
Tried this,
```CONNECTEDMONITOR=`LD_LIBRARY_PATH=/usr/lib/nvidia-current /usr/lib/nvidia-current/bin/nvidia-xconfig --query-gpu-info
``````

 it is giving error,

> NVIDIA: could not open the device file /dev/nvidiactl (No such file or directory).
> 
> ERROR: Unable to query GPU information

help me

**Comment by Web-E** [comment]
Tried another clean install, first gear shows up, 2nd gear window did not appear.
See here  https://lh5.googleusercontent.com/-5jdfBfeYfPw/TlgB5dSPLvI/AAAAAAAAA1A/UjSV5fbfJGo/s800/Screenshot-1.png 

Tried `optirun glxgears` , it run with > 500 FPS
Opened google chorme (13.0.782.215  )with optirun, webgl could not be deteced in test pages.

Rebooted, tried `o ptirun glxgears` shows error
see
 https://lh5.googleusercontent.com/-MsO2q6l9tXk/TlgB42oFRVI/AAAAAAAAA08/b5t9Pggvo7A/s800/Screenshot-2.png

**Comment by MrMEEE** [comment]
ok.. please try:

rm /etc/pm/power.d/ironhide-disablecard-on-powerup

and reboot and see if it works..

also please run ironhide-bugreport

**Comment by Web-E** [comment]
It worked!!!...
But after I run `optirun glxgears` , after sometime it shows error.Can't disable card... here is a screen shot .. https://lh6.googleusercontent.com/-tgmT_HIAtuw/TlksZi1aCAI/AAAAAAAAA1E/1J5YKpVju3g/s800/Screenshot-1.png
Also submitted the bug-report.

**Comment by Web-E** [comment]
Seems to be solved. 
Killed orphan process optirun. Rebooted, first disable card.Then tried to run optirun.Still now got no problem.
Thanks for help.

**Comment by MrMEEE** [comment]
Just uploaded new version to ppa.. please try that when its compiled.. and report back... thanks

**Comment by rockorequin** [comment]
Does the new version remove the enablecard part of the enablecard+disablecard instruction on reboot, ie as per the workaround patrici0 found in https://github.com/MrMEEE/bumblebee/issues/552? I tried ironhide a couple of days ago, but immediately ran into this problem (nvidia failing to load, saying 'no device found') and it was subsequently very difficult to uninstall ironhide at that point because apt-get uninstall kept failing with with 'no device found' early on in the uninstall process. So I'm a bit wary of trying it again.

**Comment by MrMEEE** [comment]
@rockorequin:

Yes the new version has a new fixed and enhanced disable script that (I hope) works on all systems...

**Comment by MrMEEE** [comment]
@rockorequin:

also I think I know what problem you ran into uninstalling... And i'll fix that... but if you need to, just 

rm /usr/local/bin/ironhide-\* before uninstalling...

**Comment by Web-E** [comment]
Yea.. its working fine.. I got one suggestion , while configuring ironhide.. first the gears shows up.. when the prompt came for second gear.. it is showing 
`Another ironhide powered application is running, keeping ironhide alive.
Error: could not unload nvidia module, leaving card turned on` 
The second gear didn't come up.. but ignoring this is ok.. but it shows `dpkg return error code 1` which make the installation not completed. 
I think, the glxgear not closing properly after first prompt.. Can u check that... or let the use run configuration on his own.. just instruct to run `ironhide-configuration`

**Comment by rockorequin** [comment]
ironhide is not working correctly for me with the new PPA. Installation says that the power configuration failed. However, the problem is that the Xserver is failing to start. I can enable the card and modprobe nvidia-current successfully, and the syslog shows it all working, but the Xorg.8.log file has:

[   143.883](II) LoadModule: "nvidia"
[   143.883](WW) Warning, couldn't open module nvidia
[   143.883](II) UnloadModule: "nvidia"
[   143.883](II) Unloading nvidia
[   143.883](EE) Failed to load module "nvidia" (module does not exist, 0)

**Comment by MrMEEE** [comment]
@Web-E: Thanks, I'll look into it..

@rockorequin: could you please open a new issue on this problem and run ironhide-bugreport.....

**Comment by rockorequin** [comment]
Reinstalling nvidia-current fixed the problem for me: glxgears is running now.

**Comment by rockorequin** [comment]
Except that reinstalling nvidia-current killed the intel 3d configuration. I tried reinstalling ironhide, which mostly worked (the second set of glxgears didn't appear), but the default libglx configuration is still for nvidia rather than intel. Doesn't ironhide change this anymore?
