### ISSUE TITLE
Ironhide installation in ubuntu 11.10 failed

### ISSUE THREAD

**Issue by RadeDell** [MrMEEE/ironhide#207]
During ironhide installation failure was reported - test failed. Laptop is Dell-System-Inspiron-N7110, intel+nvidia GT 525M, CPU i3

After installation optirun command in terminal shows following:
# :~$ optirun glxgears
- Starting Ironhide X server ironhide... 
- The Ironhide Xserver failed to start. Please check /var/log/Xorg.8.log
                                                                                                                               [fail] 
  ironhide could not be started - optirun cannot be executed.

Also, additional drivers - 'NVIDIA accelerated graphics driver (post-release updates)(version current updates) from Ubuntu X Swat, is activated 'and currently in use.', but NVIDIA X Server Settings shows famous 'You do not appear to be using the NVIDIA X driver.  Please edit your X configuration file (just run `nvidia-xconfig` as root), and restart the X server.' If I do so, after reboot black screen appears, and I have to back up xorg.conf etc. to normally boot into OS. 3D acceleration doesn't work.

**Comment by kedzie** [comment]
You need to run `optirun nvidia-settings` to use the NVidia X Server Settings -you need to be running the ironhide xorg.conf & xorg.conf.nvidia for this to work.  If you use nvidia-xconfig you are effectivily not using Ironhide & trying to use the Nvidia card directly (which is impossible due to Optimus technology, the whole reason you're using Ironhide in the first place).  
  But keep in mind that `optirun` is this only useful for external monitor which is connected directly to the NVidia card.  in my case, Dell XPS-17,  the HDMI port is connected to the NVidia card while the DisplayPort is connected to the integrated Intel GPU.  If you are trying to use 3d acceleration in the ubuntu desktop on your mobile display then you don't need optirun.  ironhide will send all 3d rendering commands to the nvidia card, which outputs jpegs for every frame, which are then sent to the integrated GPU for display.

**Comment by RadeDell** [comment]
In the mean time I (finally) realized how all these things work. Now everything works fine. Thank you anyway for your reply
